version: '2'
services:
  skeleton:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: skeleton:latest
    ports:
      - 8000:8000
    volumes:
      - .:/skeleton
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: skeleton
  db:
    image: postgres:11.5
    volumes:
      - skeleton-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  skeleton-db:
    external:
      name: skeleton-db
